database:
  path: "hotel_bookings.db"  
api:
  backend_url: "https://ai-booking-insights.onrender.com"  
  streamlit_url: "https://ai-booking-insights.streamlit.app/"  

faiss:
  model_name: "all-MiniLM-L6-v2"  
  num_neighbors: 5  

llm:
  provider: "groq"  
  model: "gemma2-9b-it"  

logging:
  level: "INFO"  
  log_file: "logs/app.log"  
